### ISSUE TITLE
nats-streaming source configs

### ISSUE THREAD

**Issue by rickyshrestha** [uw-labs/substrate#11]
Make AsyncMessageSourceConfig properties in nats-streaming to public.

	url -> URL
	clusterID  -> ClusterID
	subject -> Subject
	consumerGroup -> ConsumerGroup

**Comment by mjgarton** [comment]
see https://github.com/uw-labs/substrate/pull/9

This will do what you want (and more) once merged, which should be in the coming days.

**Comment by mjgarton** [comment]
#9  is merged now, please let me know if that does what you need and we can close this.

**Comment by mjgarton** [comment]
@rickyshrestha ^^

**Comment by rickyshrestha** [comment]
@mjgarton that looks good to me.
