### ISSUE TITLE
[suggestion] [nats-streaming] Expose durable connection parameter

### ISSUE THREAD

**Issue by thinktainer** [uw-labs/substrate#60]
If one passes an empty queue-group parameter then the client creates that subscription as a non durable. This is surprising behavior. Rather than trying to hide the underlying subscription model, it should be possible for a user to specify exactly what they want. 
I suggest exposing the durable parameter as a configuration option. The matrix of these options would then look like this:

### durable not set, and queue group set
queue subscription with durable name "substrate" and configured queue name
### durable set and queue group not set
regular (non queuegroup) subscription with configured durable name
### neither durable nor queue group set
regular (non durable, non queue group) subscription, with warning that this is a non permanent subscription

**Comment by thinktainer** [comment]
related to #56 and #55

**Comment by mjgarton** [comment]
What would you currently expect to happen if passing an empty queue group?

Do you think we can make these changes without breaking compatibility with current users?  If so, PR welcome.

**Comment by basia-horwath** [comment]
I support this suggestion 100%. I would currently like to use the 2nd scenario, but I cannot. 

I would just change the 1st scenario to not set any default value for durable, as the behaviour might then be confusing. 

If somebody wants to use durable, they will have to explicitly set it.

**Comment by basia-horwath** [comment]
<img width="726" alt="Screen Shot 2019-04-29 at 16 03 46" src="https://user-images.githubusercontent.com/9569852/56905627-76aaf780-6a98-11e9-92d0-a65ddf702d9c.png">

**Comment by thinktainer** [comment]
If there's no objections to this going in I'll prepare a patch shortly @mjgarton @SpeedyCoder

**Comment by SpeedyCoder** [comment]
I would maybe consider using queue group as the durable name in case the durable name is not set to match the behaviour of the current implementation. We can alternatively return an error in that case in order to force users to specify the durable name...  Overall I would prefer things to error rather than using a default name like substrate...

**Comment by thinktainer** [comment]
My point of view is that the best thing to do is to mirror the underlying implementation. So if a durable name is not specified you get a non durable queue subscription. From a users point of view I think this is the least surprising.
