### ISSUE TITLE
Add noop sink implementation

### ISSUE THREAD

**Issue by brunoluiz** [uw-labs/substrate#85]
In case a service needs to run with writing operations disabled temporarily, a `noop://` sink implementation would be nice.

This is would be specially useful in case a consumer wants to rebuild its internal state without triggering any integration.

**Comment by mjgarton** [comment]
When you say "temporarily" do you mean for the lifetime of the sink?  I think you do but I'm just clarifying.

**Comment by brunoluiz** [comment]
The temporarily would be until a specific internal state is restored, for example

**Comment by nick-jones** [comment]
Resolved by #90
